name: Build

on:
  pull_request: {}
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # We aren't using the global node setup by this action, but it
      # adds the problem matchers for eslint, tsc, etc.
      - name: Set up Node
        uses: actions/setup-node@v2.5.0
      # The default tsc problem matcher that came with setup-node does
      # not parse line/column numbers correctly.
      #
      # See: https://github.com/actions/setup-node/pull/125
      #
      # This uses the official $tsc problem matcher from vscode:
      # https://github.com/microsoft/vscode/blob/eec3db0bf3027c1aeea19ed6083d7cf3fae9d67f/extensions/typescript-language-features/package.json#L973-L982
      #
      # ::add-matcher is documented here:
      # https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers
      - name: Set up tsc problem matcher
        run: echo "::add-matcher::${GITHUB_WORKSPACE}/.github/tsc.json"
      - name: Set up Volta
        uses: volta-cli/action@v1
      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: vendor/yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Set up yarn
        run: yarn config set cache-folder vendor/yarn-cache
      - name: Install dependencies
        run: yarn install --non-interactive --pure-lockfile
      - name: Lint (hbs)
        id: lint-hbs
        continue-on-error: true
        run: yarn lint:hbs
      - name: Lint (js)
        id: lint-js
        continue-on-error: true
        run: yarn lint:js
      - name: Lint (glint)
        id: lint-glint
        continue-on-error: true
        run: yarn lint:glint
      - name: Check lints
        if: |
          steps.lint-hbs.outcome == 'failure' ||
          steps.lint-js.outcome == 'failure' ||
          steps.lint-glint.outcome == 'failure'
        run: |
          echo "Linting failed:"
          echo "  HBS: {{steps.lint-hbs.outcome}}"
          echo "  JS: {{steps.lint-js.outcome}}"
          echo "  Glint: {{steps.lint-glint.outcome}}"
          exit 1

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Volta
        uses: volta-cli/action@v1
      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: vendor/yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Set up yarn
        run: yarn config set cache-folder vendor/yarn-cache
      - name: Install dependencies
        run: yarn install --non-interactive --pure-lockfile
      - name: Run tests
        run: yarn test:ember

  ember-try:
    timeout-minutes: 30
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - ember-3.25
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Volta
        uses: volta-cli/action@v1
      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: vendor/yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Set up yarn
        run: yarn config set cache-folder vendor/yarn-cache
      - name: Install dependencies (yarn)
        run: yarn install --non-interactive --pure-lockfile
      - name: Setup ember-try scenario
        run: >-
          yarn ember try:one ${{ matrix.scenario }} --skip-cleanup ---
          '[ -z "$EMBROIDER_TEST_SETUP_OPTIONS" ] || echo "EMBROIDER_TEST_SETUP_OPTIONS=$EMBROIDER_TEST_SETUP_OPTIONS" >> $GITHUB_ENV'
      - name: Build
        run: yarn ember build --environment test
      - name: Run tests
        run: yarn test:ember --path dist
